apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cibuilds
  namespace: ci-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
